%YAML 1.0
n_camera: 4
camera_model: OPENCV_FISHEYE
cam_0:
  #T_ci
  T_cam_imu:
   - [0.9999820070808519, 0.002092894399275579, -0.00562185979765123, -0.011409455342203188]
   - [-0.0020838953862633756, 0.9999965389066579, 0.0016060992261498314, 0.015007430866851341]
   - [0.005625201735944803, -0.0015943549600417664, 0.9999829074227675, -0.01132119616200758]
   - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  distortion_coeffs: [-0.032407669645234734, -0.005428819341943016, 0.0050957405500591975,
    -0.003381286838521175]
  distortion_model: equidistant
  intrinsics: [828.4186253771514, 829.5696169855162, 690.6943431029506, 313.7908082898818]
  resolution: [1280, 800]
  rostopic: /cam0/image_raw
  timeshift_cam_imu: -0.008328208863264398
cam_1:
  T_cam_imu:
   - [-0.013848796310809486, -0.005069168594344409, -0.9998912512721094, -0.04083944186963972]
   - [-0.0010405199065818935, 0.9999866808402847, -0.005055240880049569, 0.012526859398883646]
   - [0.9999035594291414, 0.0009703977501158245, -0.013853886427311779, -0.06469305555347991]
   - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  distortion_coeffs: [-0.03297921551942553, -0.002215271997986912, 0.0019331213253299365,
    -0.0026922509576251044]
  distortion_model: equidistant
  intrinsics: [827.3645283689242, 828.5282310073628, 627.6397316266692, 357.64472638867534]
  resolution: [1280, 800]
  rostopic: /cam1/image_raw
  timeshift_cam_imu: -0.008390458957382836
cam_2:
  T_cam_imu:
   - [-0.9999145141477624, -0.007541686418531278, 0.010681168597564, 0.014733934388278247]
   - [-0.00747220395404956, 0.9999507602902397, 0.006530173278079181, 0.012933391203717958]
   - [-0.010729891179044295, 0.006449803170422655, -0.9999216316663769, -0.0790737604627606]
   - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  distortion_coeffs: [-0.033811453910106294, 0.00016393852653905512, 0.0015354004681495332,
    -0.0034981044944942825]
  distortion_model: equidistant
  intrinsics: [827.0451447153899, 828.0912485971809, 610.2680595931803, 454.4650118817843]
  resolution: [1280, 800]
  rostopic: /cam2/image_raw
  timeshift_cam_imu: -0.008421173644803133
cam_3:
  T_cam_imu:
   - [0.006241933905061503, -0.006607531837979255, 0.9999586885387496, 0.03680095339172018]
   - [-0.0007367686393356596, 0.9999778673656494, 0.006612257619067589, 0.021277317284419683]
   - [-0.9999802475214689, -0.0007780114773680243, 0.0062369275323790885, -0.03349183324938506]
   - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  distortion_coeffs: [-0.03817655065912944, 0.01607313444992231, -0.02557268541068299,
    0.011915823857516047]
  distortion_model: equidistant
  intrinsics: [828.2670769039811, 829.6427566475511, 651.8663075892625, 413.9765353088789]
  resolution: [1280, 800]
  rostopic: /cam3/image_raw
  timeshift_cam_imu: -0.008433485271999235
