%YAML 1.0

n_camera: 2
camera_model: OPENCV_FISHEYE
cam_0:
  cam_overlaps: []
  T_cam_imu:
   - [1.0, 0.0, 0.0, 0.0]
   - [0.0, 1.0, 0.0, 0.0]
   - [0.0, 0.0, 1.0, 0.0]
   - [0.0, 0.0, 0.0, 1.0]

  distortion_coeffs: [3.5288239272270545e-02, 1.1295099162062125e-02, -1.2560577445170789e-02, 1.5718516313034637e-03]
  distortion_model: radtan
  intrinsics: [8.4902286309205283e+02, 8.4912789169067889e+02, 1.4359811789467601e+03, 1436.596422815]
  resolution: [2880, 2880]
  rostopic: /cam0/image_raw
cam_1:
  cam_overlaps: []
  T_cam_imu:
   - [-1.0, 0.0, 0.0, 0.0]
   - [0.0, 1.0, 0.0, 0.0]
   - [0.0, 0.0, -1.0, 0.0]
   - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [2.9927651916837512e-02, 1.7093066108100560e-02,  -1.5049881128296305e-02, 1.9214866953023036e-03]
  distortion_model: radtan
  intrinsics: [8.5603353474149583e+02, 8.5576178835291773e+02,  1441.03863113, 1.4383883963447911e+03]
  resolution: [2880, 2880]
  rostopic: /cam1/image_raw
