%YAML 1.0
n_camera: 6
camera_model: OPENCV_FISHEYE
cam_0:
  cam_overlaps: []
  T_cam_imu:
   - [0.00955624, -0.999945, 0.00438403, 0.837711]
   - [-0.999952, -0.00956649, -0.00232397, -0.127577]
   - [0.00236578, -0.00436161, -0.999988, -3.28109]
   - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-3.1765110627423189e-02, 2.4968704212155975e-02, -3.8110221162906667e-02,
    1.7822655919445606e-02]
  distortion_model: radtan
  intrinsics: [1.2182898170491239e+03, 1.2188189736921743e+03, 1.4324204142391527e+03, 1919.840690181]
  resolution: [2880, 3840]
  rostopic: /cam0/image_raw
cam_1:
  cam_overlaps: []
  T_cam_imu:
   - [0.0170402, -0.504131, -0.863459, 1.10729]
   - [-0.999853, -0.00708893, -0.015593, -0.134408]
   - [0.00173993, 0.863598, -0.504178, -4.61593]
   - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-2.1469215225327107e-02, -3.9555848004541816e-02, 1.1084148975495639e-01,
    -9.7486647185189318e-02]
  distortion_model: radtan
  intrinsics: [1.2181926520591139e+03, 1.2192329496630057e+03, 1.4352835025633028e+03, 1908.438222551]
  resolution: [2880,3840]
  rostopic: /cam1/image_raw
cam_2:
  cam_overlaps: []
  T_cam_imu:
   - [-0.00624227, 0.502665, -0.864459, 0.0837556]
   - [-0.99998, -0.00247116, 0.00578394, -0.0821421]   
   - [0.000771173, 0.864478, 0.502671, -5.47413]
   - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-3.3887090913895135e-02, 2.2756355967897195e-02, -5.0896076172532854e-02,
    3.8995937324989634e-02]
  distortion_model: radtan
  intrinsics: [1.2220175339770067e+03, 1.2234711054937809e+03, 1.4320090049200130e+03, 1931.296245136]
  resolution: [2880,3840]
  rostopic: /cam2/image_raw
cam_3:
  cam_overlaps: []
  T_cam_imu:
   - [0, 1, 0, -0.327226]
   - [-1, 0, 0, 0.293058]
   - [0, 0, 1, -4.97678]
   - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-2.8779479252426431e-02, 2.7042461021216210e-02, -7.6060134586981049e-02,
    6.7164187739446449e-02]
  distortion_model: radtan
  intrinsics: [1.2175817901495291e+03, 1.2175112176138969e+03, 1.4508263382611403e+03, 1909.526991142]
  resolution: [2880,3840]
  rostopic: /cam3/image_raw
cam_4:
  cam_overlaps: []
  T_cam_imu:
   - [0.0201484, 0.513108, 0.858087, -1.22097]
   - [-0.99975, 0.00201223, 0.0222715, 0.181486]   
   - [0.00970104, -0.858321, 0.513021, -4.26243]
   - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-2.5805289987881837e-02, 6.4236099579761258e-03, 5.5016931039492643e-03, -1.8786474774307216e-02]
  distortion_model: radtan
  intrinsics: [1.2196766695322442e+03, 1.2203479480323074e+03, 1.4231247863236397e+03, 1921.105819963]
  resolution: [2880,3840]
  rostopic: /cam4/image_raw
cam_5:
  cam_overlaps: []
  T_cam_imu:
   - [-0.0198053, -0.517369, 0.855533, -0.179533]
   - [-0.999765, 0.0177696, -0.0123983, 0.13298]
   - [-0.00878799, -0.855578, -0.517599, -2.9983]
   - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-2.9840647965254083e-02, 1.9245253299741416e-02, -2.9982978148259648e-02,
    1.3775268981665076e-02]
  distortion_model: radtan
  intrinsics: [1.2216480653420883e+03, 1.2210205248024290e+03, 1.4429706965190810e+03, 1909.090443016]
  resolution: [2880,3840]
  rostopic: /cam5/image_raw
